controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cristina_drimbarean:
    path: /crisdrimb
    controller: App\Controller\CrisDrimbController::main
    methods: GET