controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Bibicu_Dorin:
    path: /BibicuDorin
    controller: App\Controller\BibicuDorinController::index
Bibicu_Dorin_biografie:
    path: /BibicuDorin/biografie
    controller: App\Controller\BibicuDorinController::Bibicu_Dorin_biografie
Bibicu_Dorin_home:
    path: /BibicuDorin/home
    controller: App\Controller\BibicuDorinController::Bibicu_Dorin_home
Bibicu_Dorin_activitateaStiintifica:
    path: /BibicuDorin/activitateaStiintifica
    controller: App\Controller\BibicuDorinController::Bibicu_Dorin_activitateaStiintifica
Bibicu_Dorin_activitateaDidactica:
    path: /BibicuDorin/activitateaDidactica
    controller: App\Controller\BibicuDorinController::Bibicu_Dorin_activitateaDidactica
Bibicu_Dorin_contact:
    path: /BibicuDorin/contact
    controller: App\Controller\BibicuDorinController::Bibicu_Dorin_contact

movies:
    path: /movies
    controller: App\Controller\MoviesController::index
    methods: GET

cristina_drimbarean:
    path: /crisdrimb
    controller: App\Controller\CrisDrimbController::main
    methods: GET
