controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

<<<<<<< HEAD
Bibicu_Dorin:
    path: /BibicuDorin
    controller: App\Controller\BibicuDorinController::index
biografie:
    path: /biografie
    controller: App\Controller\BibicuDorinController::biografie
home:
    path: /home
    controller: App\Controller\BibicuDorinController::home
activitateaStiintifica:
    path: /activitateaStiintifica
    controller: App\Controller\BibicuDorinController::activitateaStiintifica
activitateaDidactica:
    path: /activitateaDidactica
    controller: App\Controller\BibicuDorinController::activitateaDidactica
contact:
    path: /contact
    controller: App\Controller\BibicuDorinController::contact
=======
cristina_drimbarean:
    path: /crisdrimb
    controller: App\Controller\CrisDrimbController::main
    methods: GET
>>>>>>> 949c7fe10f7ca1905fdcb4fe69e1a27bf5c2b389
